name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.8'

            - name: pip install this package
              run: |
                  pip3 install . 

            - name: pip install pytest and mypy
              run: |
                  pip3 install pytest mypy
                  pip3 install pytest 

            - name: Run mypy
              run: mypy .

            - name: Run Pytest
              run: pytest -v tests
